alice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from alice.views import HomeScreen
from blog.views import HomeScreen, PostList, AddComment 

from . import views
from reservation import views as reservation_views
from reservation.views import confirm_reservation, search_reservation, reservation_details, delete_reservation, reserve_table, update_reservation


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("allauth.urls")),
    path('reserve_table/', reserve_table, name='reserve_table'),
    path('reviews/', PostList.as_view(), name='reviews'),
    path('add_comment/', AddComment.as_view(), name='add_comment'),
    path('menu/', views.menu, name='menu'),
    path('barmenu/', views.barmenu, name='barmenu'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('signup/', views.signup, name='signup'),
    path('confirm_reservation/<str:reservation_id>/', confirm_reservation,
         name='confirm_reservation'),       
    path('search_reservation/', search_reservation,
         name='search_reservation'),
    path('reservation_details/<str:reservation_id>/',
         reservation_details, name='reservation_details'),
    path('update_reservation/<str:reservation_id>/', update_reservation,
         name='update_reservation'),
    path('delete_reservation/', delete_reservation, name='delete_reservation'),
    path('failure/', views.failure, name='failure'),
    path("", HomeScreen.as_view(), name="HomeScreen")
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from . import views
from django.urls import path
from .views import PostList, AddComment


urlpatterns = [
    path('reviews/', views.PostList.as_view(), name='post_list'),
    path('add_comment/', views.AddComment.as_view(), name='add_comment'),  
    path('', views.HomeScreen.as_view(), name='home'),
]

reservation/urls.py
from django.urls import path
from . import views
from .views import search_reservation, delete_reservation, update_reservation, my_booking, confirm_reservation


app_name = "reservation"

urlpatterns = [
    
    path('', views.reserve_table, name='reserve_table'),
    ]

reservation/models.py
from collections import namedtuple
from datetime import date, timedelta, datetime
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models
from django.core.exceptions import ValidationError
import math
import uuid


class Customer(models.Model):
    """
    Model representing a customer.

    Attributes:
    - name: The name of the customer.
    - email: The email address of the customer.
    - number_of_persons: The number of persons in the customer's reservation.

    Methods:
    - clean: Validate the customer instance.
    """
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=200)
    number_of_persons = models.PositiveIntegerField()

    def clean(self):
        if self.number_of_persons <= 0:
            raise ValueError("Number of customers must be larger than 0")
        if self.number_of_persons > 15:
            raise ValidationError(
                "Sorry, we cannot seat more than 15 customers per reservation")


TABLE_TIME_CHOICES = [
    ("1", "15:00-17:00",),
    ("2", "16:00-18:00",),
    ("3", "17:00-19:00",),
    ("4", "18:00-20:00",),
    ("5", "19:00-21:00",),
    ("6", "20:00-22:00",),
    ]


class ReservationManager(models.Manager):
    """
    Manager for the Reservation model.

    Methods:
    - make_reservation: Make a reservation based on the provided information.
    """
    def make_reservation(
            self, name, email, number_of_persons, date, booking_time):
        existing_reservations = Reservation.objects.filter(
            date=date, booking_time=booking_time)
        used_tables = existing_reservations.values('tables')
        used_table_ids = []
        for u_table in used_tables:
            used_table_ids.append(u_table['tables'])
       
        available = Table.objects.exclude(id__in=used_table_ids)
        if available.count() == 0:
            return {'available': False}
        requested_tables = math.ceil(number_of_persons / 4.0)

        if available.count() < requested_tables:
            return {'available': False}
        new_reservation = Reservation(
            name=name,
            email=email,
            number_of_persons=number_of_persons,
            date=date,
            booking_time=booking_time)
        new_reservation.save()

        for a_table in available[:requested_tables]:
            new_reservation.tables.add(a_table)
        new_reservation.save()
        
        is_available = False
        tables = []

        return {
            "available": True,
            "tables": new_reservation.tables,
            "reservation_id": new_reservation.id
        }


class Reservation(models.Model):
    """
    Model representing a reservation.

    Attributes:
    - reservation_id: The unique ID of the reservation.
    - name: The name associated with the reservation.
    - email: The email address associated with the reservation.
    - number_of_persons: The number of persons in the reservation.
    - date: The date of the reservation.
    - tables: The tables associated with the reservation.
    - booking_time: The booking time slot for the reservation.

    Methods:
    - save: Save the reservation to the database.
    - __str__: Return a string representation of the reservation.
    """
    reservation_id = models.UUIDField(default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=200, default='example@example.com')
    number_of_persons = models.PositiveIntegerField()
    date = models.DateField(default=timezone.now)
    tables = models.ManyToManyField(
        'reservation.Table', related_name='reservations')
    booking_time = models.CharField(
        max_length=50, default=1, choices=TABLE_TIME_CHOICES)

    objects = ReservationManager()

    def save(self, *args, **kwargs):
        if not self.reservation_id:
            self.id = self.generate_reservation_id()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name} ({self.reservation_id})'
        

class Table(models.Model):
    """
    Model representing a table.

    Attributes:
    - name: The name of the table.
    - capacity: The capacity of the table.

    Methods:
    - __str__: Return a string representation of the table.
    """
    name = models.CharField(max_length=50, default='placeholder')
    capacity = models.IntegerField()

    def __str__(self):
        return f'Table {self.id}'

reservation/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from .forms import ReservationForm
from bootstrap_datepicker_plus.widgets import DateTimePickerInput
from django.utils import timezone
from django.views.generic import CreateView
from django.urls import reverse
from .models import Reservation
from django.contrib import messages
from django.http import HttpResponseRedirect
import uuid
from django.db.models import Q
from django.views.decorators.http import require_POST
from django.views.decorators.http import require_http_methods


# This is the Reservation Creation and Reading section


def reserve_table(request):
    """
    Handle the reservation form submission and display reservation page.

    Parameters:
    - request: The HTTP request object.

    Returns:
    - If the request method is 'POST' and the form is valid, redirect to the
    reservation details page.
    - If the request method is 'POST' and the form is invalid, render the
    reservation page with form errors.
    - If the request method is 'GET', render the reservation page.
    """
    new_reservation = {}
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():       
            reservation_date = form.cleaned_data['date']        

            bad_reservation = False
            if reservation_date < timezone.now().date():
                messages.warning(
                    request, "Reservation date cannot be in the past.")
                bad_reservation = True
           
            if form.cleaned_data['number_of_persons'] < 1:
                messages.warning(
                    request, "Reservation must be at least one person.")
                bad_reservation = True

            if bad_reservation:
                context = {'form': form, "new_reservation": new_reservation}
                return render(request, 'reservation/reservation.html', context)
            
            new_reservation = Reservation.objects.make_reservation(
                form.cleaned_data['name'],
                form.cleaned_data['email'],
                form.cleaned_data['number_of_persons'],
                form.cleaned_data['date'],
                form.cleaned_data['booking_time'])
            if new_reservation['available']:
                url = reverse(
                    'reservation_details', args=[new_reservation[
                        'reservation_id']])
                return redirect(url)

            else:
                context = {'form': form, "new_reservation": new_reservation}
                messages.warning(
                    request, "Sorry, your reservation size is too large")
                return render(request, 'reservation/reservation.html', context)                
            
    else:
        form = ReservationForm()
    context = {'form': form, "new_reservation": new_reservation}
    return render(request, 'reservation/reservation.html', context)


def confirm_reservation(request, reservation_id):
    """
    Display the confirmation page for a specific reservation.

    Parameters:
    - request: The HTTP request object.
    - reservation_id: The ID of the reservation.

    Returns:
    - If the reservation with the specified ID is found, render the
    confirmation page with the reservation details.
    - If the reservation with the specified ID is not found, return a
    404 response.
    """
    reservation = get_object_or_404(Reservation, reservation_id=reservation_id)
    return render(
        request, 'reservation_details.html', {'reservation': reservation})


def reservation_details(request, reservation_id):
    """
    Display the details page for a specific reservation.

    Parameters:
    - request: The HTTP request object.
    - reservation_id: The ID of the reservation.

    Returns:
    - If the reservation with the specified ID is found, render the details
    page with the reservation details.
    - If the reservation with the specified ID is not found, return a
    404 response.
    """
    reservation = get_object_or_404(Reservation, id=reservation_id)
    return render(
        request, 'reservation_details.html', {'reservation': reservation})


def table_booking(request):
    """
    Handle the table booking form submission and display failure page.

    Parameters:
    - request: The HTTP request object.

    Returns:
    - If the request method is 'POST' and the form is valid, redirect to the
    reservation modal page.
    - If the request method is 'POST' and the form is invalid, render the
    failure page with form errors.
    - If the request method is 'GET', render the failure page with an empty
    form.
    """
    if request.method == 'POST':
        form = TableForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('reservationModal')
    else:
        form = TableForm()

    return render(request, 'reservation/failure.html', {'form': form})


# This is the Researvation Update section

@require_http_methods(["GET", "POST"])
def search_reservation(request):
    """
    Handle the search reservation form submission and display the reservation
    details page.

    Parameters:
    - request: The HTTP request object.

    Returns:
    - If the request method is 'POST' and the search query is valid, redirect
    to the reservation details page.
    - If the request method is 'POST' and the search query is invalid, render
    the search reservation page with an error message.
    - If the request method is 'GET', render the search reservation page.
    """
    if request.method == 'POST':
        search_name = request.POST.get('search_name')
        search_id = request.POST.get('search_id')

        if search_name or search_id:
            reservations = Reservation.objects

            if search_name:
                reservations = reservations.filter(name__icontains=search_name)
            
            if search_id:
                reservations = reservations.filter(id=search_id)

            if reservations:
                reservation_id = reservations[0].id
                return redirect(
                    'reservation_details', reservation_id=reservation_id)
            else:
                messages.warning(
                    request, 'Sorry, No reservation found for that info.')
        else:
            messages.warning(request, 'Please provide a search query.')

    return render(request, 'search_reservation.html')


def update_reservation(request, reservation_id):
    """
    Handle the reservation update form submission and display the reservation
    page.

    Parameters:
    - request: The HTTP request object.
    - reservation_id: The ID of the existing reservation.

    Returns:
    - If the request method is 'POST' and the form is valid, redirect to the
    reservation details page for the updated reservation.
    - If the request method is 'POST' and the form is invalid, render the
    reservation page with form errors.
    - If the request method is 'GET', render the reservation page with an
    empty form.
    """

    existing_reservation = get_object_or_404(
        Reservation, reservation_id=reservation_id)
    new_reservation = {}
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():         
            reservation_date = form.cleaned_data['date']         

            bad_reservation = False
            if reservation_date < timezone.now().date():
                messages.warning(
                    request, "Reservation date cannot be in the past.")
                bad_reservation = True
           
            if form.cleaned_data['number_of_persons'] < 1:
                messages.warning(
                    request, "Reservation must be at least one person.")
                bad_reservation = True

            if bad_reservation:
                context = {'form': form, "new_reservation": new_reservation}
                return render(request, 'reservation/reservation.html', context)
            
            new_reservation = Reservation.objects.make_reservation(
                form.cleaned_data['name'],
                form.cleaned_data['email'],
                form.cleaned_data['number_of_persons'],
                form.cleaned_data['date'],
                form.cleaned_data['booking_time'])
            if new_reservation['available']:
                existing_reservation.delete()
                url = reverse(
                    'reservation_details', args=[new_reservation[
                        'reservation_id']])
                return redirect(url)

            else:
                context = {'form': form, "new_reservation": new_reservation}
                messages.warning(
                    request, "Sorry, your reservation size is too large")
                return render(request, 'reservation/reservation.html', context)               
            
    else:
        form = ReservationForm()
    context = {'form': form, "new_reservation": new_reservation}
    return render(request, 'reservation/reservation.html', context)


# This is the Delete Reservation section:


def delete_reservation(request):
    if request.method == 'POST':
        reservation_id = request.POST["reservation_id"]
        reservation = get_object_or_404(Reservation, pk=reservation_id)
        reservation.delete()
    return render(request, 'delete_reservation.html')

templates/aboutus.html
{% extends 'base.html' %} {% block content %}

<!-- Main -->
<main class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
            <div class="">
                <div class="">
                    <div class="clearfix">
                        <div class="">
                            <img src="https://res.cloudinary.com/dkkxjgoqr/image/upload/v1670066744/Alices%20Restaurant/old_house_owvyft.jpg"
                                style="height:auto" alt="an image of the building from the 50's in black and white">
                        </div>
                        <div class="align-items-center">
                            <h3>Icon of the Harbor</h3>
                            <p class="justify-content-center">
                                The Home of Alice's Restaurant, with its simple and clean design
                                language, has been a landmark in Stockholm since 1955. It was designed by the
                                well-known architect Peter Celsing back in 1949 and was the first architect-designed
                                pier side gas station in Sweden. With its humble and yet sleek design, this building has
                                been the centerpiece of the inner harbor for over 70 years.</p>

                        </div>
                    </div>
                </div>
                <div class="">
                    <div class="clearfix">
                        <div class="">
                            <img src="https://res.cloudinary.com/dkkxjgoqr/image/upload/v1670066744/Alices%20Restaurant/over_harbor_spmewu.jpg"
                                style="height:auto" alt="an image of wine and food overlooking the harbour">
                        </div>
                        <div class="align-items-center">
                            <h3>These times they are a changing</h3>
                            <p class="kustify-content-center">
                                After a number of different businesses, such as
                                tourist office, ice cream bar, cafe and pizzeria, the time finally came to transform the
                                iconic structure into a pure restaurant and brasserie with bars and outdoor seating. The
                                future looks as bright as a glass of champagne overlooking the calm harbor</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="/site.webmanifest">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.1/css/hover-min.css"
        type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Jquiry -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script> -->
    <title>Alice's Restaurant</title>
</head>

<body class="container-fluid row flex-column">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 justify-content-around">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'HomeScreen' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'menu' %}"> Menu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'barmenu' %}"> Drinks Menu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#footer">Contact / Hours</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews' %}">Reviews</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'aboutus' %}">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reserve_table' %}">Reserve a Table</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8 offset-md-2 col-lg-6">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>


    {% block content %}


    {% endblock %}

    <div class="col-lg-12 col-md-6 col-sm-4 align-items-center justify-content-center text-center">
        <a href="{% url 'reserve_table' %}" class="btn btn-outline-primary align-items-center">
            <h2>Book A Table</h2>
        </a>
        <a href="{% url 'search_reservation' %}" class="btn btn-outline-primary align-items-center">
            <h2>My Booking</h2>
        </a>
    </div>
    <!-- Footer -->
    <footer class="container-fluid" id="footer">
        <div id="footer-details" class="row">
            <div class="col-sm-4">
                <h5 class="uppercase general-sub">Location</h5>
                <div class="sqs-block-content">
                    <p id="Location"><strong>Alice's Restaurant</strong><br>
                        Kajplats 15, Strandvagen<br>
                        114 56 Stockholm<br>
                        <a href="https://www.google.com/maps/place/Strandv%C3%A4gen+12,+114+56+Stockholm,+Sweden/@59.3311936,18.0821878,99m/data=!3m1!1e3!4m5!3m4!1s0x465f9d50ba312521:0x2d99d7b4e6ccb006!8m2!3d59.331265!4d18.0825199?shorturl=1"
                            target="_blank" aria-label="">
                            Open in Google Maps</a></p>
                    <h5><strong>Contact</strong><br></h5>
                    <strong>Phone</strong>: +46 (0) 8 555 02 01<br>
                    <strong>Email</strong>: info@alicesrestaurant.com</p>
                </div>
            </div>
            <div class="col-sm-4">
                <h5 class="uppercase general-sub">Short Cuts</h5>
                <p class="inline-block">
                    <a href="{% url 'reserve_table' %}">Book a Table</a>
                    <br>
                    <a href="{% url 'HomeScreen' %}">Home</a>
                    <br>
                    <a href="{% url 'menu' %}">Food Menu</a>
                    <br>
                    <a href="{% url 'barmenu' %}">Drinks Menu</a>
                    <br>
                    <a href="{% url 'aboutus' %}">About Us</a>
                    <br>
                    <a href="{% url 'account_signup' %}">Sign Up</a>
                    <br>
                    <a href="{% url 'reviews' %}">Reviews</a>
                    <br>
            </div>
            <div class="col-sm-4">
                <h5 class="uppercase general-sub">Social</h5>
                <ul class="list-inline social-links">
                    <li class="list-inline-item">
                        <a target="_blank" href="https://facebook.com">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                            <span class="sr-only">Facebook</span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a target="_blank" href="https://twitter.com">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                            <span class="sr-only">Twitter</span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a target="_blank" href="https://YouTube.com">
                            <i class="fa fa-youtube" aria-hidden="true"></i>
                            <span class="sr-only">YouTube</span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a target="_blank" href="https://Instagram.com">
                            <i class="fa fa-instagram" aria-hidden="true"></i>
                            <span class="sr-only">Instagram</span>
                        </a>
                    </li>
                </ul>

                <div class="sqs-block-content">
                    <p class="">
                        <h5><strong>Opening Hours</strong></h5>
                        <strong>Wednesday</strong>: 15:00 - 21:00<br>
                        <strong>Thursday</strong>: 15:00 - 22:00<br>
                        <strong>Friday</strong>: 15:00 - 1:00<br>
                        <strong>Saturday</strong>: 11:00 - 1:00<br>
                        <strong>Sunday</strong>: 11:00 - 21:00<br>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
    </script>
    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 3000);
    </script>
</body>

</html>

templates/booking.html
{% extends 'base.html' %}

{% block content %}
<!-- Main -->
<main class="row">
    <div class="col-sm-6 col-md-12 align-items-center light-bg">
        <div class="container-fluid">
            <div>
                <h2>When Would You Like to Join Us?</h2>
            </div>
        </div>

        <form>

        </form>
    </div>
</main>

{% endblock %}

templates/delete_reservation.html
{% extends 'base.html' %}

{% block content %}
<main class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-xs-12 col-md-6">
            <h2>Your Reservation has been deleted, hope to see you again soon</h2>
        </div>
    </div>
</main>

{% endblock %}

templates/login.html
{% extends "openid/base.html" %}

{% load i18n %}

{% block head_title %}OpenID Sign In{% endblock %}

{% block content %}

<h1>{% trans 'OpenID Sign In' %}</h1>


<form id="openid_login_form" class="openid_login" method="post" action="{% url 'openid_login' %}">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Sign In</button>
</form>

{% endblock %}

templates/reservation.html
{% extends 'base.html' %}

{% block content %}
<!-- Main -->
<main class="row">
    <div class="col-sm-6 col-md-12 align-items-center light-bg">
        <div class="container-fluid">
            <div>
                <h2>When Would You Like to Join Us?</h2>
            </div>
        </div>

        <form action="" method="POST">
            {% csrf_token %}
            {{form}}

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</main>

{% endblock %}

templates/reservation_details.html
{% extends 'base.html' %}

{% block content %}

<main class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-md-6">
      <h2>Thank you for booking with us, here are your details:</h2>
      <p><strong>Reservation Name:</strong> {{ reservation.name }}</p>
      <p><strong>Email:</strong> {{ reservation.email }}</p>
      <p><strong>Reservation Date:</strong> {{ reservation.date }}</p>
      <p><strong>Reservation Time:</strong> {{ reservation.get_booking_time_display }}</p>
      <p><strong>Reservation ID:</strong> {{ reservation.id }}</p>

      <br>
      <form method="POST" action="{% url 'delete_reservation' %}">
        {% csrf_token %}
        <input type="hidden" name="reservation_id" value="{{ reservation.id }}">
        <div class="d-flex justify-content-center flex-wrap">
          <button type="submit" class="btn btn-outline-danger align-items-center"
            onclick="return confirm('Are you sure you want to delete this reservation?')">Delete
            Reservation</button>
        </div>
      </form>
      <div class="d-flex justify-content-center flex-wrap">
        <a href="{% url 'update_reservation' reservation_id=reservation.reservation_id  %}">
          <button class="btn btn-outline-primary align-items-center">Change Reservation</button>
        </a>
      </div>

    </div>
  </div>

</main>
{% endblock %}